name: flirtbees
description: Flirtbees
version: 1.0.22+22

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2+1
  dio: ^3.0.9
  shared_preferences: ^0.5.7+3
  socket_io_client: ^0.9.11
  flutter_screenutil: ^1.1.0
  provider: ^4.1.3
  flutter_webrtc: ^0.2.8
  intl: ^0.16.0
  intl_translation: ^0.17.9
  permission_handler: ^5.0.1+1
  flutter_slidable: ^0.5.4
  camera: ^0.5.8+2
  image_picker_gallery_camera: ^0.1.6
  nested_navigators: ^1.0.9
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  fluttertoast: ^7.0.1+1
  sign_in_with_apple: ^2.5.1
  flutter_facebook_login: ^3.0.0
  flutter_image_compress: ^0.7.0
  modal_bottom_sheet: ^0.2.0+1
  firebase_messaging: ^6.0.16
  device_info: ^0.4.0+4
  flutter_local_notifications: ^1.4.4+3
  get: ^3.4.6
  rxdart: ^0.23.1
  flutter_incall_manager:
    git:
      url: https://github.com/nhancv/flutter-incall-manager.git

flutter_intl:
  enabled: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  lint: ^1.2.0
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.3

  
flutter_icons:
  image_path: "assets/base/icons/app_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path_android: "assets/base/icons/app_icon.png"
  image_path_ios: "assets/base/icons/app_icon.png"
  adaptive_icon_background: "assets/base/icons/app_icon_adaptive.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/base/icons/app_icon_adaptive.png" # only available for Android 8.0 devices and above
# To Generate icon
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/base/icons/
    - assets/base/fonts/
    - assets/app/icons/
    - assets/app/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/base/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/base/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/base/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/base/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/base/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/base/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/app/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/app/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/app/fonts/Lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900
